baseURL = "https://example.com"
languageCode = "en-us"
title = "Your Name"
theme = "minimal-light"

[params]
  # Basic Information
  position = "Ph.D. Student"
  affiliation = "Your Affiliation"
  email = "yourname (at) example.edu"

  # Search Engine Optimization (SEO)
  keywords = "minimal light"
  description = "A simple and elegant hugo theme for academic personal homepage"
  canonical = "https://minimal-light-theme.yliu.me/"

  # Links
  google_scholar = "https://scholar.google.com/"
  cv_link = "assets/files/curriculum_vitae.pdf"
  github_link = "https://github.com/"
  linkedin = "https://www.linkedin.com/"
  twitter = "https://twitter.com/"

  # Images
  avatar = "./assets/img/avatar.png"
  favicon = "./assets/img/favicon.png"
  favicon_dark = "./assets/img/favicon-dark.png"

  # Other options
  enable_footnote = true
  auto_dark_mode = true
  font = "Serif" # or "Sans Serif"
  google_analytics = "UA-111540567-4"
